name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Give execute permission to mvnw
      - name: Make mvnw executable
        run: chmod +x backend/mvnw

      # Now build the backend
      - name: Build Backend
        run: |
          cd backend
          ./mvnw clean install -DskipTests

#      - name: Qodana Scan
#        uses: JetBrains/qodana-action@v2025.3
#        with:
#          args: --save-report --save-baseline